server:
  port: 8070

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dragon?serverTimezone=Asia/Seoul
    username: angel
    password: 1234