server:
  port: 8070

spring:
  profiles:
    include: apikey

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#mybatis
mybatis:
  type-aliases-package: com.space.meong.*
  mapper-locations:
    - /mapper/**/*.xml #mapper 폴더 안에 어느 폴더에 있든 xml로 끝나는 파일